"""add short_name to tenant

Revision ID: fb8e97540d6e
Revises: 046d33ce6194
Create Date: 2026-04-03 12:10:24.981694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8e97540d6e'
down_revision: Union[str, None] = '046d33ce6194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('short_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'short_name')
    # ### end Alembic commands ###
