"""add member_statuses to tenant

Revision ID: 28e758a5dafa
Revises: be632fa3ec0b
Create Date: 2026-04-04 19:26:14.554107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e758a5dafa'
down_revision: Union[str, None] = 'be632fa3ec0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Seed with English labels for neutrality. Tenants created through the
    # API receive locale-specific labels via core/seeds.py at creation time.
    op.add_column('tenants', sa.Column('member_statuses', sa.Text(), nullable=False, server_default=sa.text("'[{\"key\":\"active\",\"label\":\"Active\"},{\"key\":\"inactive\",\"label\":\"Inactive\"},{\"key\":\"resigned\",\"label\":\"Resigned\"},{\"key\":\"terminated\",\"label\":\"Terminated\"},{\"key\":\"deceased\",\"label\":\"Deceased\"}]'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'member_statuses')
    # ### end Alembic commands ###
