"""link invitations to members

Revision ID: 84226652616f
Revises: d5b41e70949f
Create Date: 2026-08-01 18:41:41.799325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84226652616f'
down_revision: Union[str, None] = 'd5b41e70949f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('member_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'member_id')
    # ### end Alembic commands ###
