"""add member number format fields

Revision ID: c44800946477
Revises: 834ee01b8714
Create Date: 2026-04-04 15:12:22.791754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44800946477'
down_revision: Union[str, None] = '834ee01b8714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('member_number_format', sa.String(length=100), nullable=False, server_default=sa.text("'{NUM}'")))
    op.add_column('tenants', sa.Column('member_number_prefix', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('member_number_next', sa.Integer(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'member_number_next')
    op.drop_column('tenants', 'member_number_prefix')
    op.drop_column('tenants', 'member_number_format')
    # ### end Alembic commands ###
