"""extend tenant with contact address and details

Revision ID: 046d33ce6194
Revises: 5921d2dc52c9
Create Date: 2026-04-02 20:16:48.146571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046d33ce6194'
down_revision: Union[str, None] = '5921d2dc52c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    op.add_column('tenants', sa.Column('founded_at', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('registration_court', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'registration_court')
    op.drop_column('tenants', 'registration_number')
    op.drop_column('tenants', 'founded_at')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'state')
    op.drop_column('tenants', 'city')
    op.drop_column('tenants', 'zip_code')
    op.drop_column('tenants', 'street')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'email')
    # ### end Alembic commands ###
