"""add soft delete to entries

Revision ID: 6d40b7e807b3
Revises: f7b4d2e81a53
Create Date: 2026-07-26 14:06:31.403080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d40b7e807b3'
down_revision: Union[str, None] = 'f7b4d2e81a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_entries_deleted_at'), 'entries', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_deleted_at'), table_name='entries')
    op.drop_column('entries', 'deleted_at')
    # ### end Alembic commands ###
