"""add members table

Revision ID: be632fa3ec0b
Revises: c44800946477
Create Date: 2026-04-04 16:23:42.306583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be632fa3ec0b'
down_revision: Union[str, None] = 'c44800946477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'member_number')
    )
    op.create_index(op.f('ix_members_deleted_at'), 'members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_members_tenant_id'), 'members', ['tenant_id'], unique=False)
    op.create_index('ix_members_tenant_name', 'members', ['tenant_id', 'last_name', 'first_name'], unique=False)
    op.create_index('ix_members_tenant_status', 'members', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_members_tenant_status', table_name='members')
    op.drop_index('ix_members_tenant_name', table_name='members')
    op.drop_index(op.f('ix_members_tenant_id'), table_name='members')
    op.drop_index(op.f('ix_members_deleted_at'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
