"""add tax and nonprofit fields to tenant

Revision ID: a0161c039dee
Revises: fb8e97540d6e
Create Date: 2026-04-03 12:57:17.984231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0161c039dee'
down_revision: Union[str, None] = 'fb8e97540d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tax_number', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('tax_office', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('is_nonprofit', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tenants', sa.Column('nonprofit_since', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'nonprofit_since')
    op.drop_column('tenants', 'is_nonprofit')
    op.drop_column('tenants', 'tax_office')
    op.drop_column('tenants', 'tax_number')
    # ### end Alembic commands ###
