"""add disciplines table

Revision ID: a4b24ba82095
Revises: 76365fb79339
Create Date: 2026-04-07 12:10:50.983080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b24ba82095'
down_revision: Union[str, None] = '76365fb79339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('federation', sa.String(length=50), nullable=False),
    sa.Column('federation_id', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.String(length=50), nullable=True),
    sa.Column('caliber', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('scoring_unit', sa.String(length=50), nullable=False),
    sa.Column('scoring_mode', sa.String(length=20), nullable=False),
    sa.Column('shot_count', sa.Integer(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_disciplines_category', 'disciplines', ['category'], unique=False)
    op.create_index('ix_disciplines_federation', 'disciplines', ['federation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disciplines_federation', table_name='disciplines')
    op.drop_index('ix_disciplines_category', table_name='disciplines')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
