"""Official discipline definitions for German shooting sports.

Sources:
- DSB Sportordnung (SpO) — https://www.dsb.de/sportordnung
- BDS Sporthandbuch — https://www.bfrds.de
- ISSF Rules — https://www.issf-sports.org

Each entry follows the DSB/BDS official numbering where available.
"""

DISCIPLINES: list[dict] = [
    # =========================================================================
    # DSB — Deutscher Schützenbund
    # Nummerierung nach DSB Sportordnung (SpO)
    # =========================================================================
    # --- Luftdruck ---
    {
        "slug": "dsb-1.10",
        "name": "Luftgewehr Auflage",
        "short_name": "LG Auflage",
        "description": "Luftgewehr mit Auflage, stehend. 40 Schuss Einzelwertung auf die LG-Scheibe in 10m Entfernung. Altersklasse: Senioren.",
        "federation": "DSB",
        "federation_id": "1.10",
        "category": "Luftdruck",
        "distance": "10m",
        "caliber": "4.5mm Diabolo",
        "target_type": "air_rifle_10m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 40,
    },
    {
        "slug": "dsb-1.35",
        "name": "Luftgewehr Dreistellungskampf",
        "short_name": "LG 3-Stellung",
        "description": "Luftgewehr 3-Stellung (kniend, liegend, stehend). Je 20 Schuss pro Stellung, 60 Schuss gesamt auf 10m.",
        "federation": "DSB",
        "federation_id": "1.35",
        "category": "Luftdruck",
        "distance": "10m",
        "caliber": "4.5mm Diabolo",
        "target_type": "air_rifle_10m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    {
        "slug": "dsb-1.40",
        "name": "Luftgewehr",
        "short_name": "LG 10m",
        "description": "Luftgewehr stehend freihändig. 60 Schuss auf die LG-Scheibe in 10m Entfernung. Olympische Disziplin.",
        "federation": "DSB",
        "federation_id": "1.40",
        "category": "Luftdruck",
        "distance": "10m",
        "caliber": "4.5mm Diabolo",
        "target_type": "air_rifle_10m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    {
        "slug": "dsb-2.10",
        "name": "Luftpistole Auflage",
        "short_name": "LP Auflage",
        "description": "Luftpistole mit Auflage. 40 Schuss auf die LP-Scheibe in 10m Entfernung. Altersklasse: Senioren.",
        "federation": "DSB",
        "federation_id": "2.10",
        "category": "Luftdruck",
        "distance": "10m",
        "caliber": "4.5mm Diabolo",
        "target_type": "air_pistol_10m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 40,
    },
    {
        "slug": "dsb-2.40",
        "name": "Luftpistole",
        "short_name": "LP 10m",
        "description": "Luftpistole freihändig. 60 Schuss auf die LP-Scheibe in 10m Entfernung. Olympische Disziplin.",
        "federation": "DSB",
        "federation_id": "2.40",
        "category": "Luftdruck",
        "distance": "10m",
        "caliber": "4.5mm Diabolo",
        "target_type": "air_pistol_10m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    # --- Kleinkaliber Gewehr ---
    {
        "slug": "dsb-3.10",
        "name": "KK-Liegendkampf 50m",
        "short_name": "KK 50m liegend",
        "description": "Kleinkalibergewehr liegend. 60 Schuss auf die KK-50m-Scheibe. Olympische Disziplin.",
        "federation": "DSB",
        "federation_id": "3.10",
        "category": "Kleinkaliber",
        "distance": "50m",
        "caliber": ".22 LR",
        "target_type": "smallbore_rifle_50m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    {
        "slug": "dsb-3.05",
        "name": "KK-Dreistellungskampf 50m",
        "short_name": "KK 3x40",
        "description": "Kleinkalibergewehr 3-Stellung (kniend, liegend, stehend). 3x40 Schuss = 120 Schuss gesamt auf 50m.",
        "federation": "DSB",
        "federation_id": "3.05",
        "category": "Kleinkaliber",
        "distance": "50m",
        "caliber": ".22 LR",
        "target_type": "smallbore_rifle_50m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 120,
    },
    {
        "slug": "dsb-3.40",
        "name": "KK-Gewehr 100m",
        "short_name": "KK 100m",
        "description": "Kleinkalibergewehr auf 100m. 40 Schuss liegend auf die KK-100m-Scheibe.",
        "federation": "DSB",
        "federation_id": "3.40",
        "category": "Kleinkaliber",
        "distance": "100m",
        "caliber": ".22 LR",
        "target_type": "smallbore_rifle_100m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 40,
    },
    # --- Kleinkaliber Pistole ---
    {
        "slug": "dsb-4.10",
        "name": "Freie Pistole 50m",
        "short_name": "FP 50m",
        "description": "Freie Pistole auf 50m. 60 Schuss freihändig. Eine der anspruchsvollsten Pistolendisziplinen.",
        "federation": "DSB",
        "federation_id": "4.10",
        "category": "Kleinkaliber",
        "distance": "50m",
        "caliber": ".22 LR",
        "target_type": "free_pistol_50m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    {
        "slug": "dsb-4.20",
        "name": "KK-Sportpistole 25m",
        "short_name": "SP 25m",
        "description": "Sportpistole 25m. Präzisions- und Duellserie. 30+30 = 60 Schuss. Olympische Disziplin (Frauen).",
        "federation": "DSB",
        "federation_id": "4.20",
        "category": "Kleinkaliber",
        "distance": "25m",
        "caliber": ".22 LR",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    {
        "slug": "dsb-4.25",
        "name": "KK-Standardpistole 25m",
        "short_name": "StaPi 25m",
        "description": "Standardpistole 25m. 3 Serien à 5 Schuss in verschiedenen Zeitlimits (150s, 20s, 10s).",
        "federation": "DSB",
        "federation_id": "4.25",
        "category": "Kleinkaliber",
        "distance": "25m",
        "caliber": ".22 LR",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    {
        "slug": "dsb-4.30",
        "name": "Schnellfeuerpistole 25m",
        "short_name": "SFP 25m",
        "description": "Schnellfeuerpistole 25m. 5 Scheiben, 5 Schuss in 8s/6s/4s. Olympische Disziplin (Männer).",
        "federation": "DSB",
        "federation_id": "4.30",
        "category": "Kleinkaliber",
        "distance": "25m",
        "caliber": ".22 LR",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    # --- Großkaliber Pistole (DSB) ---
    {
        "slug": "dsb-4.60",
        "name": "GK-Sportpistole 25m",
        "short_name": "GK SP 25m",
        "description": "Großkaliber-Sportpistole 25m. Präzisions- und Duellserie mit Großkaliberpistole (mind. 7.62mm).",
        "federation": "DSB",
        "federation_id": "4.60",
        "category": "Großkaliber",
        "distance": "25m",
        "caliber": "9mm / .45 ACP",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 60,
    },
    # --- Flinte (DSB) ---
    {
        "slug": "dsb-5.10",
        "name": "Trap",
        "short_name": "Trap",
        "description": "Wurfscheibenschießen Trap. 125 Wurfscheiben, 5 Stände. Olympische Disziplin.",
        "federation": "DSB",
        "federation_id": "5.10",
        "category": "Flinte",
        "distance": "—",
        "caliber": "12/70",
        "target_type": None,
        "scoring_unit": "Treffer",
        "scoring_mode": "highest_wins",
        "shot_count": 125,
    },
    {
        "slug": "dsb-5.30",
        "name": "Skeet",
        "short_name": "Skeet",
        "description": "Wurfscheibenschießen Skeet. 125 Wurfscheiben, 8 Stände. Olympische Disziplin.",
        "federation": "DSB",
        "federation_id": "5.30",
        "category": "Flinte",
        "distance": "—",
        "caliber": "12/70",
        "target_type": None,
        "scoring_unit": "Treffer",
        "scoring_mode": "highest_wins",
        "shot_count": 125,
    },
    # =========================================================================
    # BDS — Bund Deutscher Sportschützen
    # =========================================================================
    # --- Kurzwaffen ---
    {
        "slug": "bds-kw-1",
        "name": "BDS Pistole 25m Präzision",
        "short_name": "BDS Pi 25m",
        "description": "BDS Kurzwaffen-Disziplin. Pistole 25m, Präzisionsschießen auf BDS-Scheibe Nr. 5. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "KW 1",
        "category": "Kurzwaffen",
        "distance": "25m",
        "caliber": "9mm",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-kw-2",
        "name": "BDS Revolver 25m Präzision",
        "short_name": "BDS Rev 25m",
        "description": "BDS Kurzwaffen-Disziplin. Revolver 25m, Präzisionsschießen. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "KW 2",
        "category": "Kurzwaffen",
        "distance": "25m",
        "caliber": ".357 Mag / .38 Spl",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-kw-5",
        "name": "BDS KK-Pistole 25m",
        "short_name": "BDS KK Pi 25m",
        "description": "BDS Kurzwaffen-Disziplin. Kleinkaliber-Pistole 25m. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "KW 5",
        "category": "Kurzwaffen",
        "distance": "25m",
        "caliber": ".22 LR",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    # --- Langwaffen ---
    {
        "slug": "bds-lw-1",
        "name": "BDS Sportgewehr Selbstlader oV",
        "short_name": "BDS SL oV 100m",
        "description": "BDS Langwaffen-Disziplin. Sportgewehr Selbstlader mit offener Visierung auf 100m. "
        "Scheibe Nr. 5. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 1",
        "category": "Langwaffen",
        "distance": "100m",
        "caliber": ".223 Rem / .308 Win",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-lw-2",
        "name": "BDS Unterhebelrepetierer",
        "short_name": "BDS UHR 100m",
        "description": "BDS Langwaffen-Disziplin. Unterhebelrepetierer auf 100m. Scheibe Nr. 5. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 2",
        "category": "Langwaffen",
        "distance": "100m",
        "caliber": ".357 Mag / .44 Mag",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-lw-3",
        "name": "BDS Dienstsportgewehr offene Kimme",
        "short_name": "BDS DSG oK 100m",
        "description": "BDS Langwaffen-Disziplin. Dienstsportgewehr mit offener Kimme auf 100m. "
        "Scheibe Nr. 5. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 3",
        "category": "Langwaffen",
        "distance": "100m",
        "caliber": ".223 Rem / .308 Win",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-lw-4",
        "name": "BDS Dienstsportgewehr Diopter",
        "short_name": "BDS DSG Dio 100m",
        "description": "BDS Langwaffen-Disziplin. Dienstsportgewehr mit geschlossener Kimme/Diopter auf 100m. "
        "Scheibe Nr. 5. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 4",
        "category": "Langwaffen",
        "distance": "100m",
        "caliber": ".223 Rem / .308 Win",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-lw-5",
        "name": "BDS KK-Gewehr 50m",
        "short_name": "BDS KK 50m",
        "description": "BDS Langwaffen-Disziplin. KK-Gewehr auf 50m. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 5",
        "category": "Langwaffen",
        "distance": "50m",
        "caliber": ".22 LR",
        "target_type": "smallbore_rifle_50m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-lw-6",
        "name": "BDS GK-Gewehr 100m Zielfernrohr",
        "short_name": "BDS GK ZF 100m",
        "description": "BDS Langwaffen-Disziplin. Großkalibergewehr mit Zielfernrohr auf 100m. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 6",
        "category": "Langwaffen",
        "distance": "100m",
        "caliber": ".223 Rem / .308 Win",
        "target_type": "sport_pistol_25m",
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    {
        "slug": "bds-lw-10",
        "name": "BDS GK-Gewehr 300m",
        "short_name": "BDS GK 300m",
        "description": "BDS Langwaffen-Disziplin. Großkalibergewehr auf 300m. 30 Schuss Wertung.",
        "federation": "BDS",
        "federation_id": "LW 10",
        "category": "Langwaffen",
        "distance": "300m",
        "caliber": ".308 Win",
        "target_type": None,
        "scoring_unit": "Ringe",
        "scoring_mode": "highest_wins",
        "shot_count": 30,
    },
    # --- BDS Flinte ---
    {
        "slug": "bds-fl-trap",
        "name": "BDS Trap",
        "short_name": "BDS Trap",
        "description": "BDS Flinten-Disziplin. Wurfscheibenschießen Trap.",
        "federation": "BDS",
        "federation_id": "FL Trap",
        "category": "Flinte",
        "distance": "—",
        "caliber": "12/70",
        "target_type": None,
        "scoring_unit": "Treffer",
        "scoring_mode": "highest_wins",
        "shot_count": 25,
    },
    {
        "slug": "bds-fl-skeet",
        "name": "BDS Skeet",
        "short_name": "BDS Skeet",
        "description": "BDS Flinten-Disziplin. Wurfscheibenschießen Skeet.",
        "federation": "BDS",
        "federation_id": "FL Skeet",
        "category": "Flinte",
        "distance": "—",
        "caliber": "12/70",
        "target_type": None,
        "scoring_unit": "Treffer",
        "scoring_mode": "highest_wins",
        "shot_count": 25,
    },
    {
        "slug": "bds-fl-sporting",
        "name": "BDS Sporting",
        "short_name": "BDS Sporting",
        "description": "BDS Flinten-Disziplin. Sporting/Parcours.",
        "federation": "BDS",
        "federation_id": "FL Sporting",
        "category": "Flinte",
        "distance": "—",
        "caliber": "12/70",
        "target_type": None,
        "scoring_unit": "Treffer",
        "scoring_mode": "highest_wins",
        "shot_count": 25,
    },
]
